language: julia
sudo: required
dist: trusty
os:
  - linux
  - osx
julia:
  - 0.7
  - nightly
notifications:
  email: false
branches:
  only:
    - master
    - /^release-.*$/
# matrix:
#  allow_failures:
#  - julia: 0.7
after_success:
  - julia -e 'using LCMCore; cd(pathof(LCMCore)); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

