language: julia
sudo: required
dist: trusty
os:
  - linux
  - osx
julia:
  - 0.5
  - nightly
notifications:
  email: false
branches:
  only:
    - master
script:
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - julia -e 'Pkg.clone("https://github.com/rdeits/CMakeWrapper.jl.git")'
 - julia -e 'Pkg.build("CMakeWrapper")'
 - julia -e 'Pkg.clone(pwd()); Pkg.build("LCMCore"); Pkg.test("LCMCore"; coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("LCMCore")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
