language: julia
sudo: required
dist: trusty
os:
  - linux
  - osx
julia:
  - 0.7
  - nightly
notifications:
  email: false
branches:
  only:
    - master
matrix:
 allow_failures:
 - julia: 0.7  # due to bugs fixed after 0.7.beta
after_success:
  - julia -e 'cd(Pkg.dir("LCMCore")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

