language: julia
sudo: required
dist: trusty
os:
  - linux
  - osx
julia:
  - 0.6
notifications:
  email: false
branches:
  only:
    - master
    - release-0.6
after_success:
  - julia -e 'cd(Pkg.dir("LCMCore")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

